"""
В ячейке ниже представлен код генерирующий DataFrame,
которая состоит всего из 1 столбца.
Ваша задача перевести его в one hot вид.
Сможете ли вы это сделать без get_dummies?

import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI'lst})
data.head()
"""

# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i3lSm-Ry58kvFMdf9GbKuDW98oKiMvxR
"""

import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI': lst})
unique_values = data['whoAmI'].unique()
for value in unique_values:
    data[value] = (data['whoAmI'] == value).astype(int)
data.drop('whoAmI', axis=1, inplace=True)
data.head()
